[colors]
foreground = "#566162"
background = "#d9f5ff"
cursor_bg = "#566162"
cursor_border = "#566162"
cursor_fg = "#d9f5ff"
selection_bg = "#2c96e2"
selection_fg = "#566162"

ansi = ["#e2f8ff", "#e73330", "#576600", "#7e5d00", "#1c6da7", "#d73884", "#279a91", "#737d7e"]
brights = ["#d9f5ff", "#e73330", "#576600", "#7e5d00", "#1c6da7", "#d73884", "#279a91", "#566162"]

[colors.tab_bar]
inactive_tab_edge = "#87ddff"
background = "#191b28"

[colors.tab_bar.active_tab]
fg_color = "#1c6da7"
bg_color = "#d9f5ff"

[colors.tab_bar.inactive_tab]
bg_color = "#87ddff"
fg_color = "#41d7fc"

[colors.tab_bar.inactive_tab_hover]
bg_color = "#87ddff"
fg_color = "#1c6da7"

[colors.tab_bar.new_tab_hover]
fg_color = "#87ddff"
bg_color = "#1c6da7"

[colors.tab_bar.new_tab]
fg_color = "#1c6da7"
bg_color = "#191b28"

[metadata]
aliases = []
author = "craftzdog"
name = "Solarized Osaka Light"