[[themes]]
name = "Solarized Osaka Light"
[themes.palette]
background = "#87ddff"
foreground = "#737d7e"
black = "#d9f5ff"
red = "#e73330"
green = "#576600"
yellow = "#7e5d00"
blue = "#1c6da7"
magenta = "#d73884"
cyan = "#279a91"
white = "#d9f5ff"
bright_black = "#d9f5ff"
bright_red = "#be2420"
bright_green = "#576600"
bright_yellow = "#d14f17"
bright_blue = "#2f84be"
bright_magenta = "#af246d"
bright_cyan = "#2c96e2"
bright_white = "#566162"
