attribute = { fg = "#e73330" }
comment = { fg = "#6e8992", modifiers = ["italic"] }
"comment.block.documentation" = { fg = "#279a91" }
constant = { fg = "#279a91" }
"constant.builtin" = { fg = "#d14f17" }
"constant.builtin.boolean" = { fg = "#279a91" }
"constant.character" = { fg = "#279a91" }
"constant.character.escape" = { fg = "#f9611f" }
"constant.numeric" = { fg = "#279a91" }
"constant.numeric.float" = { fg = "#279a91" }
"constant.numeric.integer" = { fg = "#279a91" }
constructor = { fg = "#7e5d00" }
"diagnostic.error" = { underline = { style = "curl" } }
"diagnostic.hint" = { underline = { style = "curl" } }
"diagnostic.info" = { underline = { style = "curl" } }
"diagnostic.warning" = { underline = { style = "curl" } }
"diff.delta" = { fg = "#7e5d00" }
"diff.delta.moved" = { fg = "#1c6da7" }
"diff.minus" = { fg = "#e73330" }
"diff.plus" = { fg = "#576600" }
error = { fg = "#e73330" }
function = { fg = "#1c6da7" }
"function.builtin" = { fg = "#d14f17" }
"function.macro" = { fg = "#e73330" }
"function.method" = { fg = "#1c6da7" }
"function.special" = { fg = "#e73330" }
hint = { fg = "#279a91" }
info = { fg = "#1c6da7" }
keyword = { fg = "#576600", modifiers = ["italic"] }
"keyword.control" = { fg = "#576600" }
"keyword.control.conditional" = { fg = "#576600" }
"keyword.control.exception" = { fg = "#576600" }
"keyword.control.repeat" = { fg = "#576600" }
"keyword.control.return" = { fg = "#576600", modifiers = ["italic"] }
"keyword.directive" = { fg = "#e73330" }
"keyword.function" = { fg = "#576600" }
"keyword.operator" = { fg = "#576600" }
label = { fg = "#576600" }
"markup.bold" = { modifiers = ["bold"] }
"markup.heading" = { fg = "#d14f17", modifiers = ["bold"] }
"markup.heading.completion" = { bg = "#41d7fc", fg = "#737d7e" }
"markup.heading.hover" = { bg = "#585449", fg = "#6e8992" }
"markup.italic" = { modifiers = ["italic"] }
"markup.link" = { fg = "#1c6da7", underline = { style = "line" } }
"markup.link.label" = { fg = "#d14f17" }
"markup.link.text" = { fg = "#1c6da7", underline = { style = "line" } }
"markup.link.url" = { underline = { style = "line" } }
"markup.list" = { fg = "#1c6da7" }
"markup.normal.completion" = { bg = "#41d7fc", fg = "#737d7e" }
"markup.normal.hover" = { bg = "#585449", fg = "#6e8992" }
"markup.raw" = { fg = "#279a91" }
"markup.raw.inline" = { bg = "#bbd300", fg = "#7e5d00" }
"markup.strikethrough" = { modifiers = ["crossed_out"] }
namespace = { fg = "#e73330" }
operator = { fg = "#576600" }
special = { fg = "#d14f17" }
string = { fg = "#279a91" }
"string.regexp" = { fg = "#0d6b63" }
"string.special" = { fg = "#d14f17" }
tag = { fg = "#576600" }
type = { fg = "#7e5d00" }
"type.builtin" = { fg = "#7e5d00" }
"type.enum" = { fg = "#7e5d00" }
"type.enum.variant" = { fg = "#279a91" }
"ui.background" = { bg = "bg" }
"ui.cursor" = { bg = "#737d7e", fg = "#87ddff" }
"ui.cursor.match" = { bg = "#e73330", fg = "#e51000", modifiers = ["bold"] }
"ui.linenr" = { bg = "#d9f5ff", fg = "#ca9900" }
"ui.linenr.select" = { fg = "#d14f17" }
"ui.menu" = { bg = "#41d7fc", fg = "#737d7e" }
"ui.menu.scroll" = { bg = "bg", fg = "fg" }
"ui.menu.selected" = { bg = "#585449", fg = "#6e8992" }
"ui.popup" = { bg = "#d9f5ff", fg = "#ca9900" }
"ui.selection" = { bg = "bg_highlight" }
"ui.statusline" = { bg = "#87ddff", fg = "#6e7474" }
"ui.statusline.inactive" = { bg = "#d9f5ff", fg = "#737d7e" }
"ui.statusline.normal" = { bg = "blue", fg = "black" }
"ui.text" = { bg = "#d9f5ff", fg = "#737d7e" }
"ui.text.focus" = { bg = "#41d7fc" }
"ui.text.inactive" = { fg = "#6e8992", modifiers = ["italic"] }
"ui.text.info" = { fg = "#1c6da7" }
"ui.virtual.inlay-hint" = { bg = "#50d3da", fg = "#279a91" }
"ui.window" = { fg = "#41d7fc", modifiers = ["bold"] }
variable = { fg = "#737d7e" }
"variable.builtin" = { fg = "#d14f17" }
"variable.other.member" = { fg = "#279a91" }
"variable.parameter" = { fg = "#d14f17" }
warning = { fg = "#7e5d00" }

[palette]
base0 = "#9eabac"
base00 = "#637981"
base01 = "#576d74"
base02 = "#063540"
base03 = "#002c38"
base04 = "#001419"
base1 = "#adb7b7"
base2 = "#ede7d3"
base3 = "#fdf5e2"
base4 = "#ffffff"
bg = "#001419"
bg_float = "#001419"
bg_highlight = "#002c38"
bg_popup = "#001419"
bg_sidebar = "#001419"
bg_statusline = "#002c38"
black = "#001014"
blue = "#268bd3"
blue100 = "#a8daff"
blue300 = "#46acf5"
blue500 = "#268bd3"
blue700 = "#1a6397"
blue900 = "#0f3856"
border = "#001014"
cyan = "#29a298"
cyan100 = "#b7fefa"
cyan300 = "#2aeddd"
cyan500 = "#29a298"
cyan700 = "#1a6265"
cyan900 = "#103a3c"
error = "#db302d"
fg = "#839395"
fg_float = "#839395"
green = "#849900"
green100 = "#d6fead"
green300 = "#b7f900"
green500 = "#849900"
green700 = "#586600"
green900 = "#2c3300"
hint = "#29a298"
info = "#268bd3"
magenta = "#d23681"
magenta100 = "#ff75b7"
magenta300 = "#f254a0"
magenta500 = "#d23681"
magenta700 = "#af2668"
magenta900 = "#541131"
orange = "#c94c16"
orange100 = "#ff9165"
orange300 = "#f74f0c"
orange500 = "#c94c16"
orange700 = "#a13c10"
orange900 = "#5b220a"
red = "#db302d"
red100 = "#ff9a99"
red300 = "#f55350"
red500 = "#db302d"
red700 = "#b7211f"
red900 = "#570f0e"
todo = "#6d71c4"
violet = "#6d71c4"
violet100 = "#cccffe"
violet300 = "#9b9fec"
violet500 = "#6d71c4"
violet700 = "#484eb6"
violet900 = "#24275a"
warning = "#b28500"
yellow = "#b28500"
yellow100 = "#ffe899"
yellow300 = "#ffbf00"
yellow500 = "#b28500"
yellow700 = "#664c00"
yellow900 = "#332700"

